# Ngram tutorial

In [5]:
from nltk.corpus import brown

In [6]:
import nltk
tagged_words = brown.tagged_words()

## Write a function to count the number of tags. The function should be named countTags and should take a tag name as input and return tag count

In [7]:
def countTags(tag_name):
    tag_count = nltk.FreqDist(tag for word,tag in tagged_words)
    return tag_count[tag_name]

print countTags('NN')
print countTags('AT')
    

152470
97959


It should print countTags("NN") as 152470 and countTags("AT") as 97959

## Write a function to count the number of words. The function should be named countWords and should take a word name as input and return word count

In [8]:
def countWords(word_name):
    word_count = nltk.FreqDist(word for word,tag in tagged_words)
    return word_count[word_name]

print countWords('the')

62713


It should print countWords("the") as 62713

## Write code to create a dictionary (nested dictionary) where given a word it prints out tag count. 

In [9]:
def wordDict(word_name):
    cfd = nltk.ConditionalFreqDist(tagged_words)
    return dict(cfd[word_name])
#     word_tag = []
#     for word,tag in tagged_words:
#         if word == word_name:
#             word_tag.append((word,tag))
#     word_tag_count = {}
#     word_tag_count[word_name] = nltk.FreqDist(tag for word,tag in word_tag)
#     return dict(word_tag_count[word_name])

print wordDict('the')

{u'AT-TL-HL': 1, u'AT-NC': 26, u'AT': 62288, u'NIL': 3, u'AT-HL': 172, u'AT-TL': 223}


For example, assuming the dictionary created is worddict, worddict["the"] should print 
```python
{u'AT-TL-HL': 1, u'AT-NC': 26, u'NIL': 3, u'AT-TL': 223, u'AT': 62288, u'AT-HL': 172}
```

## Write code to create a dictionary (nested dictionary) where given a tag it prints out bigram tag count. 

for example, assuming the dictionary created is tagdict, tagdict["AT"] should print 
```python
{u'NP$': 62, u'JJT-TL': 3, u'WDT': 2, u'RBR+CS': 1, u'JJ': 19488, u'AP$': 1, u'RP': 1, u'(': 15, u',': 12, u'RB': 350, u'JJ-HL': 1, u'NNS': 7215, u'NN$': 907, u'NN+BEZ': 13, u'NNS$': 97, u'NIL': 1, u'--': 4, u'OD': 1251, u'FW-NN-TL': 52, u'VB-TL': 3, u'AP-TL': 2, u'NPS': 588, u'NPS-TL': 2, u'FW-JJ': 2, u'HV': 1, u'NPS$': 30, u'FW-RB': 1, u'RB-TL': 1, u'NN+HVZ': 3, u"'": 24, u'FW-CC': 1, u'NP$-TL': 17, u'PN': 149, u'NN+MD': 2, u'RB-NC': 1, u'MD': 1, u'NN-HL': 3, u'VBG-TL': 34, u'VBG': 1568, u'VBD': 2, u'VBN-TL': 390, u'VBN': 1468, u'VBZ': 1, u'NN': 48376, u'NR$-TL': 8, u'*': 4, u'.': 4, u'FW-NNS': 11, u'NP': 2230, u'NR': 218, u'FW-NN$': 1, u'``': 620, u'CC': 4, u'OD-TL': 98, u'CD': 981, u'NP-TL': 809, u'JJT': 675, u'JJS': 206, u'JJR': 630, u'PN+HVZ': 1, u'FW-JJT': 1, u'NNS$-TL': 28, u'JJ-TL': 1414, u'FW-VBN': 1, u'FW-JJ-TL': 8, u'FW-VB': 2, u'NN-TL': 2565, u"''": 7, u'CD-TL': 29, u'FW-NN-TL-NC': 1, u'PN$': 1, u')': 1, u'PPO': 1, u'PPS': 1, u'UH': 2, u'VB': 16, u'FW-IN': 7, u'RBT': 11, u'RBR': 40, u'ABN': 42, u'AP': 3007, u'BEZ-NC': 1, u'AT': 1, u'JJS-TL': 2, u'IN': 3, u'NR-TL': 208, u'FW-NNS-TL': 5, u'NN+IN': 1, u'NNS-TL': 284, u'JJR-TL': 3, u'NN$-TL': 162, u'FW-IN-TL': 4, u'IN-TL': 1, u'FW-NN': 76, u'QL': 1377}
```

For this following code can be used
```python
from nltk.util import ngrams
bigrams=ngrams(tags, 2)
```
tags parameter is the tags list from the corpus. For more details regarding ngrams usage see http://www.nltk.org/_modules/nltk/util.html

In [12]:
from nltk.util import ngrams

def tagDict(tag):
    tags = []
    bigrams = ngrams(tagged_words,2)
    for a,b in bigrams:
        if a[1] == tag:
            tags.append(b[1])
    tag_fd = nltk.FreqDist(tags)
    return dict(tag_fd)
    
    
print tagDict('AT')

{u'VBG': 1568, u'VBD': 2, u'NP$': 62, u'JJT-TL': 3, u'VBN': 1468, u'WDT': 2, u'RBR+CS': 1, u'JJ': 19488, u'VBZ': 1, u'AP$': 1, u'RP': 1, u'NN': 48376, u'NR$-TL': 8, u'(': 15, u'*': 4, u',': 12, u'.': 4, u'CD-TL': 29, u'RB': 350, u'VBN-TL': 390, u'JJ-HL': 1, u'NR': 218, u'NNS': 7215, u'FW-NN$': 1, u'``': 620, u'CC': 4, u'NN-TL': 2565, u'NN$': 907, u'CD': 981, u'NP': 2230, u'NN+BEZ': 13, u'NNS$': 97, u'NP-TL': 809, u'NIL': 1, u'--': 4, u'OD': 1251, u'JJS': 206, u'JJR': 630, u'FW-NN-TL': 52, u'VB-TL': 3, u'AP-TL': 2, u'JJR-TL': 3, u'FW-JJT': 1, u'NNS$-TL': 28, u'JJ-TL': 1414, u'NPS': 588, u'JJT': 675, u'NPS-TL': 2, u'FW-JJ-TL': 8, u'FW-JJ': 2, u'HV': 1, u"''": 7, u'FW-VB': 2, u'NPS$': 30, u'FW-NN-TL-NC': 1, u'FW-RB': 1, u'RB-TL': 1, u'PN$': 1, u'NN+HVZ': 3, u'FW-VBN': 1, u"'": 24, u')': 1, u'FW-CC': 1, u'PPO': 1, u'NP$-TL': 17, u'PPS': 1, u'FW-NNS': 11, u'PN': 149, u'UH': 2, u'VB': 16, u'OD-TL': 98, u'FW-IN': 7, u'NN+MD': 2, u'RBT': 11, u'RBR': 40, u'ABN': 42, u'RB-NC': 1, u'BEZ-NC': 1, u

## Write code to find the probability of assigning tag "AT NN" to the phrase "The man". It can be found by the product of the two probabilities $P(w_n | t_n)* P(t_n | t_{n−1})$. Assume that "AT" is the most probable tag for the word "The". 

Any reasonable assumptions can be made

In [44]:
import operator
tag, tag_count = max(wordDict('the').iteritems(), key=operator.itemgetter(1))
p_of_the_given_tag = tag_count / float(countTags(tag))
tag2, tag2_count = max(wordDict('man').iteritems(), key=operator.itemgetter(1))
p_of_man_given_tag = tag2_count / float(countTags(tag2))
bigram_tag, bigram_tag_count = max(tagDict(tag).iteritems(), key=operator.itemgetter(1))
p_of_tag2_given_tag = bigram_tag_count / float(countTags(bigram_tag))

print p_of_the_given_tag * p_of_man_given_tag * p_of_tag2_given_tag

0.00151372583369
